/*
==================================
ブロンズ層のテーブルへのロード
==================================
目的:
    内部ステージにあるcsvからブロンズ層のテーブルへとロードする
    今回、ブロンズ層では毎回フルロードを行う設定なので、COPY INTOの前にTRUNCATEを挟んでいる
*/

use role sysadmin;
use warehouse compute_wh;
use database data_warehouse;
use schema bronze;

-- CRM
TRUNCATE TABLE DATA_WAREHOUSE.BRONZE.CRM_CUST_INFO;
COPY INTO DATA_WAREHOUSE.BRONZE.CRM_CUST_INFO
FROM @DATA_WAREHOUSE.STAGING.STG_CSV_FILES/datasets/source_crm/cust_info.csv
FILE_FORMAT = DATA_WAREHOUSE.STAGING.CSV_FORMAT;

TRUNCATE TABLE DATA_WAREHOUSE.BRONZE.CRM_PRD_INFO;
COPY INTO DATA_WAREHOUSE.BRONZE.CRM_PRD_INFO
FROM @DATA_WAREHOUSE.STAGING.STG_CSV_FILES/datasets/source_crm/prd_info.csv
FILE_FORMAT = DATA_WAREHOUSE.STAGING.CSV_FORMAT;

TRUNCATE TABLE DATA_WAREHOUSE.BRONZE.CRM_SALES_DETAILS;
COPY INTO DATA_WAREHOUSE.BRONZE.CRM_SALES_DETAILS
FROM @DATA_WAREHOUSE.STAGING.STG_CSV_FILES/datasets/source_crm/sales_details.csv
FILE_FORMAT = DATA_WAREHOUSE.STAGING.CSV_FORMAT;

-- ERP
TRUNCATE TABLE DATA_WAREHOUSE.BRONZE.ERP_CUST_AZ12;
COPY INTO DATA_WAREHOUSE.BRONZE.ERP_CUST_AZ12
FROM @DATA_WAREHOUSE.STAGING.STG_CSV_FILES/datasets/source_erp/CUST_AZ12.csv
FILE_FORMAT = DATA_WAREHOUSE.STAGING.CSV_FORMAT;

TRUNCATE TABLE DATA_WAREHOUSE.BRONZE.ERP_LOC_A101;
COPY INTO DATA_WAREHOUSE.BRONZE.ERP_LOC_A101
FROM @DATA_WAREHOUSE.STAGING.STG_CSV_FILES/datasets/source_erp/LOC_A101.csv
FILE_FORMAT = DATA_WAREHOUSE.STAGING.CSV_FORMAT;

TRUNCATE TABLE DATA_WAREHOUSE.BRONZE.ERP_PX_CAT_G1V2;
COPY INTO DATA_WAREHOUSE.BRONZE.ERP_PX_CAT_G1V2
FROM @DATA_WAREHOUSE.STAGING.STG_CSV_FILES/datasets/source_erp/PX_CAT_G1V2.csv
FILE_FORMAT = DATA_WAREHOUSE.STAGING.CSV_FORMAT;